FROM maven:3-alpine AS builder
WORKDIR /usr/src/app
COPY pom.xml .
COPY src src
RUN mvn clean package -B

FROM tomcat:9.0.24-jdk8-openjdk
RUN rm -rf ./webapps/*
COPY --from=builder /usr/src/app/target/app.war ./webapps/